<!-- DATA EXPORT -->
<div class="widget widget-table">
    <div class="widget-header">
        <h3><i class="fa fa-table"></i>  Kenya Malaria prevalence per County</h3>
    </div>
    <div class="widget-content">
        <table id="datatable-data-export" class="table table-sorting table-striped table-hover table-bordered datatable">
            <thead>
            <tr>
                <th>County</th>
                <th>% Slept Under Bad Net</th>
                <th>% That had a Fever or Malaria </th>
                <th>Health spending per Person</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th>County</th>
                <th>% Slept Under Bad Net</th>
                <th>% That had a Fever or Malaria </th>
                <th>Health spending per Person</th>
            </tr>
            </tfoot>
            <tbody>
            <tr>
                <td>Nyandarua</td>
                <td>1.7%</td>
                <td>14.4%</td>
                <td>17</td>
            </tr>
            <tr>
                <td>Makueni</td>
                <td>10.8%</td>
                <td>51.1%%</td>
                <td>15</td>
            </tr>
            <tr>
                <td>Marsabit</td>
                <td>11.1%</td>
                <td>44%</td>
                <td>46</td>
            </tr>
            <tr>
                <td>Murang'a</td>
                <td>11.4%</td>
                <td>36.2%</td>
                <td>22</td>
            </tr>
            <tr>
                <td>Laikipia</td>
                <td>12.3%</td>
                <td>14.9%</td>
                <td>29</td>
            </tr>
            <tr>
                <td>Narok</td>
                <td>12.9%</td>
                <td>55.8%</td>
                <td>7</td>
            </tr>
            <tr>
                <td>Kitui</td>
                <td>13%</td>
                <td>50.5%</td>
                <td>46</td>
            </tr>
            <tr>
                <td>Kiambu</td>
                <td>14.5%</td>
                <td>22.8%%</td>
                <td>20</td>
            </tr>
            <tr>
                <td>West Pokot</td>
                <td>15.9%</td>
                <td>60.4%</td>
                <td>24</td>
            </tr>
            <tr>
                <td>Wajir</td>
                <td>18.3%</td>
                <td>54.8%</td>
                <td>21</td>
            </tr>
            <tr>
	            <td>Nandi</td>
	            <td>18.9%</td>
	            <td>50.9%%</td>
	            <td>23</td>
            </tr>
            <tr>
	            <td>Embu</td>
	            <td>21.8%</td>
	            <td>39.8%</td>
	            <td>34</td>
            </tr>
            <tr>
	            <td>Trans Nzoia</td>
	            <td>23%</td>
	            <td>34.8%</td>
	            <td>8</td>
            </tr>
            <tr>
	            <td>Meru</td>
	            <td>24%</td>
	            <td>42.6%%</td>
	            <td>22</td>
            </tr>
            <tr>
	            <td>Baringo</td>
	            <td>24.2%</td>
	            <td>14.9%</td>
	            <td>29</td>
            </tr>
            <tr>
	            <td>Bomet</td>
	            <td>26.3%</td>
	            <td>39.5%</td>
	            <td>20</td>
            </tr>
            <tr>
                <td>Kakamega</td>
                <td>22.7%</td>
                <td>37.9%</td>
                <td>23</td>
            </tr>
            <tr>
                <td>Bungoma</td>
                <td>27.8%</td>
                <td>37.6%</td>
                <td>20</td>
            </tr>
            <tr>
                <td>Vihiga</td>
                <td>28.5%</td>
                <td>33.4%</td>
                <td>10</td>
            </tr>
            <tr>
                <td>Samburu</td>
                <td>3.2%</td>
                <td>37.1%</td>
                <td>34</td>
            </tr>
            <tr>
                <td>Kirinyaga</td>
                <td>30%</td>
                <td>43.2%</td>
                <td>18</td>
            </tr>
            <tr>
                <td>Kajiado</td>
                <td>30.4%</td>
                <td>12.3%</td>
                <td>15</td>
            </tr>
            <tr>
                <td>Taita Taveta</td>
                <td>30.8%</td>
                <td>48.8%</td>
                <td>48</td>
            </tr>
            <tr>
                <td>Machakos</td>
                <td>31.7%</td>
                <td>40.9%</td>
                <td>16</td>
            </tr>
            <tr>
                <td>Kwale</td>
                <td>32.1%</td>
                <td>37.7%</td>
                <td>31</td>
            </tr>
            <tr>
                <td>Uasin Gishu</td>
                <td>33.6%</td>
                <td>43.4%</td>
                <td>13</td>
            </tr>
            <tr>
                <td>Kericho</td>
                <td>33.8%</td>
                <td>51.6%</td>
                <td>11</td>
            </tr>
            <tr>
                <td>Kisii</td>
                <td>37.8%</td>
                <td>49%</td>
                <td>26</td>
            </tr>
            <tr>
                <td>Nairobi</td>
                <td>38%</td>
                <td>37.7%</td>
                <td>7</td>
            </tr>
            <tr>
                <td>Garissa</td>
                <td>38.4%</td>
                <td>46.6%</td>
                <td>37</td>
            </tr>
            <tr>
                <td>Kilifi</td>
                <td>38.5%</td>
                <td>45.4%</td>
                <td>26</td>
            </tr>
            <tr>
                <td>Homa Bay</td>
                <td>39.6%</td>
                <td>58.3%</td>
                <td>24</td>
            </tr>
            <tr>
                <td>Mandera</td>
                <td>4.6%</td>
                <td>35.2%</td>
                <td>20</td>
            </tr>
            <tr>
                <td>Migori</td>
                <td>40.1%</td>
                <td>63%</td>
                <td>23</td>
            </tr>
            <tr>
                <td>Busia</td>
                <td>40.7%</td>
                <td>42.8%</td>
                <td>20</td>
            </tr>
            <tr>
                <td>Nyamira</td>
                <td>40.9%</td>
                <td>38.9%</td>
                <td>22</td>
            </tr>
            <tr>
                <td>Tharaka Nithi</td>
                <td>41.3%</td>
                <td>33.8%</td>
                <td>18</td>
            </tr>
            <tr>
                <td>Isiolo</td>
                <td>42.6%</td>
                <td>33.7%</td>
                <td>42</td>
            </tr>
            <tr>
                <td>Tana River</td>
                <td>45.1%</td>
                <td>63.3%</td>
                <td>19</td>
            </tr>
            <tr>
                <td>Siaya</td>
                <td>46.7%</td>
                <td>54.4%</td>
                <td>22</td>
            </tr>
            <tr>
                <td>Nyeri</td>
                <td>5.7%</td>
                <td>13.4%</td>
                <td>39</td>
            </tr>
            <tr>
                <td>Mombasa</td>
                <td>50.6%</td>
                <td>48%</td>
                <td>11</td>
            </tr>
            <tr>
                <td>Lamu</td>
                <td>51.3%</td>
                <td>63.3%</td>
                <td>50</td>
            </tr>
            <tr>
                <td>Turkana</td>
                <td>6%</td>
                <td>55.4%</td>
                <td>14</td>
            </tr>
            <tr>
                <td>Kisumu</td>
                <td>62.4%</td>
                <td>45.6%</td>
                <td>29</td>
            </tr>
            <tr>
                <td>Elgeyo/Marakwet</td>
                <td>7.5%</td>
                <td>9.4%</td>
                <td>48</td>
            </tr>
            <tr>
                <td>Nakuru</td>
                <td>9.8%</td>
                <td>0%</td>
                <td>11</td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<!-- END DATA EXPORT -->
